services:
  backend-metashark:
    image: ckala62rus/docker_php_sqlsrv-backend-new-template
    build: docker/php
    container_name: backend-metashark
    working_dir: /var/www/
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./backend/:/var/www/
      - ./docker/php/logs/:/var/log/php/
    depends_on:
      - db_pg_metashark
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
      PHP_IDE_CONFIG: serverName=PHPSTORM
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx-metashark:
    image: nginx:1.21.1
    container_name: nginx-metashark
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/config/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/certs/:/etc/nginx/certs
      - ./docker/nginx/htpasswd/:/etc/nginx/htpasswd
      - ./docker/nginx/templates/:/etc/nginx/templates
      - ./docker/nginx/logs/:/var/log/nginx
      - ./backend/:/var/www
    depends_on:
      - backend-metashark
    environment:
      NGINX_UPSTREAM: backend-metashark:9000

  redis-metashark:
    container_name: redis-metashark
    image: "redis:alpine"
    command: redis-server --requirepass 123123
    ports:
      - "6379:6379"

  redis-metashark-commander:
    container_name: redis-metashark-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: redis-new-template
      REDIS_HOST: redis-new-template
      REDIS_PORT: redis:6379
      REDIS_PASSWORD: 123123
      HTTP_USER: root
      HTTP_PASSWORD: root
    ports:
      - 8081:8081

  db_pg_metashark:
    container_name: db_pg_metashark
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata_metashark:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  pgadmin_metashark:
    image: dpage/pgadmin4:6.15
    container_name: pgadmin_metashark
    env_file:
      - ./.env
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    depends_on:
      - db_pg_metashark


volumes:
  pgdata_metashark:
    name: pgdata_metashark
